### ISSUE TITLE
AccessWidener tries to strip final from static final fields in interfaces

### ISSUE THREAD

**Issue by shedaniel** [FabricMC/access-widener#2]

**Comment by liach** [comment]
@modmuss50 Can you move this back to the loader? I don't think it's the access widener's responsibility to check if a widener is valid or not (i.e. it cannot check if a class/member ever exists; in the same way, it cannot check if the field is in an interface and the widening would produce invalid bytecode (interface fields must be public static final per jvm spec, I think)
