### ISSUE TITLE
Cannot find the target class that needs to be access-widen

### ISSUE THREAD

**Issue by HaorenXiaoming** [FabricMC/access-widener#25]
When I use access-widener, I am prompted that I cannot find the target class that needs to be access-widen.The information is as follows:
     Cause: java.lang.RuntimeException: Could not find class      (com/simibubi/create/content/logistics/trains/entity/BogeyInstance)
     Your reply will be greatly appreciated~

**Comment by Technici4n** [comment]
Access Widener only works on classes from Minecraft, you can't use it on mods.
